Label.index={0}
Label.name=Name
Label.price=Price
Label.item.description=Description
Label.item.long.description=Long Description
Label.item.short.description=Short Description
Label.item.on.sale=On Sale
Label.item.new.arrival=New Arrival
Label.item.online=Online
label.item.no=Item No.
Lable.item.id=Product ID
Label.item.quantity=Quantity
Label.item.name=Product Name
Label.item.brand=Product Brand
Lable.item.search=Searchable
Label.item.manufacture=Manufacturer
Label.item.categories=Categories
Label.item.available.stock.unit=Availabile units
Label.item.available.stock.status=Availability
text.openingBracket=(
text.closingBracket=)
text.item.notavailable=The product of [ProductID = {0}] is not online/searchable
text.heading.fill.details=Fill the details
text.label.fname=First name
text.label.lname=Last name
text.label.email=Email address
text.label.address=Address
text.label.submit=Submit
text.label.details=Details
text.label.phone=Contact no
text.label.add.cart.button=Add to Cart