## cartridge.properties for cartridge app_pavitra_storefront
    #Wed Mar 26 2025 16:58:59 GMT+0530 (India Standard Time)
    demandware.cartridges.app_pavitra_storefront.multipleLanguageStorefront=true
    demandware.cartridges.app_pavitra_storefront.id=app_pavitra_storefront
